var CANVAS_HEIGHT = 400;
var CANVAS_WIDTH = 400;
var FIXED_UPDATES_IN_A_SECOND = 30;
var FIXED_STEP_IDEAL_DURATION_MS = 1000/FIXED_UPDATES_IN_A_SECOND;
var WALK_SPEED_PIXELS_PER_SECOND = 70;
var WALK_SPEED_PIXELS_PER_UPDATE = WALK_SPEED_PIXELS_PER_SECOND/FIXED_UPDATES_IN_A_SECOND;
var STATES_HISTORY_CAPACITY = 10;
var USER_INPUT_BUFFER_CAPACITY = 10;

var ANIMATION_MANAGER = new AnimationManager();

var INPUT_EVENT_STATE = {
	"start":1,
	"end":0
};

var INPUT_EVENT_TYPE = {
	"shieldR":10,
  "shieldL":12,
  "shieldU":14,
  "shieldD":16,
	"faceR":20,
  "faceL":22,
  "faceU":24,
  "faceD":26,
	"right":30,
	"left":40,
	"down":50,
  "up":60
};

function resetUPS(ups) {
	FIXED_UPDATES_IN_A_SECOND = ups;
	FIXED_STEP_IDEAL_DURATION_MS = 1000/FIXED_UPDATES_IN_A_SECOND;
	WALK_SPEED_PIXELS_PER_UPDATE = WALK_SPEED_PIXELS_PER_SECOND/FIXED_UPDATES_IN_A_SECOND;
}
